### ISSUE TITLE
HtWire hangs until connection is closed remotely

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos-http#62]
Test case:

```java
new TextOf(
  new HtResponse(
    new HtWire("somehost"),
    "GET /some/resource HTTP/1.1\r\n" +
    "Host: somehost\r\n\r\n"
  )
).asString()
```

The code above will hang until the remote service [sends a TCP packet with the FIN flag](https://stackoverflow.com/a/611777/1623885).

The fundamental question here is: how do we tell that we have already received the entire HTTP response and thus avoid having to wait until the remote service ends the connection themselves?

We can start with [section 3.3.3 of RFC7230](https://tools.ietf.org/html/rfc7230#section-3.3.3).

Edit: can be avoided by sending the `Connection: close` header (remote service needs to behave well; usually not a problem though)

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
Job [#62](https://github.com/yegor256/cactoos-http/issues/62) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos-http/issues/62#issuecomment-397422870))

@llorllale Job [#62](https://github.com/yegor256/cactoos-http/issues/62) is already in scope

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) not enough funds available in the project, can't set budget of job [#62](https://github.com/yegor256/cactoos-http/issues/62), see [§21](http://www.zerocracy.com/policy.html#21); @llorllale[/z](https://www.0crat.com/u/llorllale) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by llorllale** [comment]
@llorllale

Keep in mind that our goals [1] do not include implementing every feature offered by other HTTP libs. 

With that said:

## Work to be done

* Need to refactor `HtWire` so that the socket is kept alive and its associated inputstream is not read at all. This opens the possibility for us to support persistent connections in the future (although would need to keep a reference to the socket if we intend to write to it again) and makes it the responsibility of `*Response` objects to properly handle network resources.
* Need to provide decorators to `HtResponse` that automatically close the inputstream, and thus the socket, on some criteria:
  * Based on `Content-Length`
  * Based on `Transfer-Encoding: chunked`

### Alternatives
As noted in the description, a workaround would be for the sender to manually include the `Connection: close` header in the request:

```java
  new HtResponse(
    new HtWire("somehost"),
    new JoinedText(
        "\r\n",
        "GET /some/resource HTTP/1.1",
        "Host: somehost",
        "Connection: close\r\n"
    ).asString()
  )
```

The problems I see with this are:
1. The user has to manually type that string. Querying network resources is typically a one-off thing in the majority of use cases outside of browsers.
2. Leaves control of the lifecycle of network resources entirely in the remote service' hands. This is unacceptable, as we must also be able to close the socket when we are finished using it.
------------------

[1] Goals not written anywhere. There is only a vague statement in the `README`: *We are well aware of competitors (most likely they are more powerful than our client, but less object-oriented)*

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#63](https://github.com/yegor256/cactoos-http/issues/63), [#64](https://github.com/yegor256/cactoos-http/issues/64) are still not solved.

**Comment by llorllale** [comment]
@llorllale fixed in  795e57c6d3c16283c56b66c62a765f5605aadd7d

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#62](https://github.com/yegor256/cactoos-http/issues/62) is now out of scope

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#64](https://github.com/yegor256/cactoos-http/issues/64), [#78](https://github.com/yegor256/cactoos-http/issues/78) are still not solved; solved: [#63](https://github.com/yegor256/cactoos-http/issues/63).

**Comment by 0pdd** [comment]
@llorllale 3 puzzles [#78](https://github.com/yegor256/cactoos-http/issues/78), [#80](https://github.com/yegor256/cactoos-http/issues/80), [#81](https://github.com/yegor256/cactoos-http/issues/81) are still not solved; solved: [#63](https://github.com/yegor256/cactoos-http/issues/63), [#64](https://github.com/yegor256/cactoos-http/issues/64).

**Comment by 0pdd** [comment]
@llorllale 3 puzzles [#80](https://github.com/yegor256/cactoos-http/issues/80), [#81](https://github.com/yegor256/cactoos-http/issues/81), [#87](https://github.com/yegor256/cactoos-http/issues/87) are still not solved; solved: [#63](https://github.com/yegor256/cactoos-http/issues/63), [#64](https://github.com/yegor256/cactoos-http/issues/64), [#78](https://github.com/yegor256/cactoos-http/issues/78).

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#81](https://github.com/yegor256/cactoos-http/issues/81), [#87](https://github.com/yegor256/cactoos-http/issues/87) are still not solved; solved: [#63](https://github.com/yegor256/cactoos-http/issues/63), [#64](https://github.com/yegor256/cactoos-http/issues/64), [#78](https://github.com/yegor256/cactoos-http/issues/78), [#80](https://github.com/yegor256/cactoos-http/issues/80).

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#81](https://github.com/yegor256/cactoos-http/issues/81), [#98](https://github.com/yegor256/cactoos-http/issues/98) are still not solved; solved: [#63](https://github.com/yegor256/cactoos-http/issues/63), [#64](https://github.com/yegor256/cactoos-http/issues/64), [#78](https://github.com/yegor256/cactoos-http/issues/78), [#80](https://github.com/yegor256/cactoos-http/issues/80), [#87](https://github.com/yegor256/cactoos-http/issues/87), [#99](https://github.com/yegor256/cactoos-http/issues/99).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#81](https://github.com/yegor256/cactoos-http/issues/81) is still not solved; solved: [#63](https://github.com/yegor256/cactoos-http/issues/63), [#64](https://github.com/yegor256/cactoos-http/issues/64), [#78](https://github.com/yegor256/cactoos-http/issues/78), [#80](https://github.com/yegor256/cactoos-http/issues/80), [#87](https://github.com/yegor256/cactoos-http/issues/87), [#98](https://github.com/yegor256/cactoos-http/issues/98), [#99](https://github.com/yegor256/cactoos-http/issues/99).
